general:
  mode: performance
  runner: diego
  device: mps

dataset:
  signal_path: data/signal_test.csv
  background_path: data/background_test.csv
  persistent_workers: True
  train:
    num_workers: 8
    batch_size: 10000
  val:
    num_workers: 4
    batch_size: 5000

model:
  n_particles: 7

train:
  n_epochs: 600
  learning_rate: 0.002
  dropout_probability: 0.1
predict:
  output_file: predictions.csv

performance:
  model_ckpt_path: lightning_logs/version_0/checkpoints/