general:
  mode: train
  runner: diego
  device: cuda

dataset:
  signal_path: data/SimpleVBF.h5
  background_path: data/SimpleQCD.h5
  persistent_workers: True
  train:
    num_workers: 8
    batch_size: 50000
  val:
    num_workers: 8
    batch_size: 20000

model:
  type: DNN
  n_particles: 5
  n_features: 40

train:
  n_epochs: 400
  learning_rate: 0.0003
  dropout_probability: 0.1
predict:
  model_ckpt_path: lightning_logs/version_0/checkpoints/
  output_file: predictions.csv
performance:
  model_ckpt_path: lightning_logs/version_0/checkpoints/