general:
  mode: performance
  runner: diego
  device: cuda

dataset:
  signal_path: data/signal_simple_polars.csv
  background_path: data/background_simple_polars.csv

model:
  n_particles: 7

train:
  n_epochs: 300

predict:
  output_file: predictions.csv

performance:
  model_ckpt_path: lightning_logs/version_0/checkpoints/