name: VBF Transformer CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: requirements.yaml
        activate-environment: vbf_ditau

    - name: Install VBF Transformer package
      run: |
        pip install -e .

    - name: Run training
      run: |
        python VBFTransformer.py --config-dir tests/configs --config-name test_config opts.mode=train

    - name: Run prediction
      run: |
        python VBFTransformer.py --config-dir tests/configs --config-name test_config opts.mode=predict

    - name: Run performance
      run: |
        python VBFTransformer.py --config-dir tests/configs --config-name test_config opts.mode=performance
